name: Todoist Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12-22/2 * * 1-5"

jobs:
  update-readme:
    name: Update todoist stats
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: "1.30.0"
          args: "--accept-routes"
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@main
        env:
          OP_CONNECT_HOST: http://100.99.73.138
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          TODOIST_API_KEY: op://home-lab/todoist-token/password
      - uses: actions/checkout@v2
      - uses: OGKevin/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{ steps.op-load-secret.outputs.TODOIST_API_KEY }}
